"""initial

Revision ID: 4faf7ab5ee2f
Revises: 
Create Date: 2023-01-17 17:18:30.268203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4faf7ab5ee2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menu',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Menu_id'), 'Menu', ['id'], unique=False)
    op.create_table('SubMenu',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('menu_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['Menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SubMenu_id'), 'SubMenu', ['id'], unique=False)
    op.create_table('Dish',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sub_menu_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sub_menu_id'], ['SubMenu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Dish_id'), 'Dish', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Dish_id'), table_name='Dish')
    op.drop_table('Dish')
    op.drop_index(op.f('ix_SubMenu_id'), table_name='SubMenu')
    op.drop_table('SubMenu')
    op.drop_index(op.f('ix_Menu_id'), table_name='Menu')
    op.drop_table('Menu')
    # ### end Alembic commands ###
