"""relation cascade3

Revision ID: d268c80160ce
Revises: d5b8fea8c594
Create Date: 2023-01-16 22:42:17.879976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd268c80160ce'
down_revision = 'd5b8fea8c594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
