"""relation cascade3

Revision ID: d5b8fea8c594
Revises: f93b8d830fd6
Create Date: 2023-01-15 21:36:31.148034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b8fea8c594'
down_revision = 'f93b8d830fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
