"""relation cascade2

Revision ID: f93b8d830fd6
Revises: f233dd70d2bf
Create Date: 2023-01-13 21:26:53.210335

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f93b8d830fd6'
down_revision = 'f233dd70d2bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
